### ISSUE TITLE
Use Laravel's Storage Facade to move Uploaded Image

### ISSUE THREAD

**Issue by reliq** [reliqarts/laravel-guided-image#19]
Use Laravel's `Storage` facade to move uploaded image instead of `$uploadedFile->move($path)`

Code ref: https://github.com/reliqarts/laravel-guided-image/blob/master/src/Services/ImageUploader.php#L99

---
Similar issue elsewhere: https://github.com/laravel/framework/issues/26783

**Comment by erko185** [comment]
I'll take this. Please write more description where you need

**Comment by reliq** [comment]
@erko185 looking forward to your PR on this. 

I must admit it might be a bit involved as I have not yet looked at how to integrate the `Storage` facade in detail. I will remove the `good first issue` label for now.

This might be helpful: https://laravel.com/docs/6.x/filesystem

**Comment by reliq** [comment]
Resolved with release https://github.com/reliqarts/laravel-guided-image/releases/tag/v2.0.0
