### ISSUE TITLE
Class ReliqArts\GuidedImage\Service\Logger cannot extend final class ReliqArts\Service\Logger

### ISSUE THREAD

**Issue by simondrevensek** [reliqarts/laravel-guided-image#25]
I'm trying to reach the photo over the url: http://127.0.0.1:8000/image/.res/58//550-_/_/_ but I keep getting this error.

**Comment by reliq** [comment]
Thank you for reporting this. The issue was fixed in [v4.4.1](https://github.com/reliqarts/laravel-guided-image/releases/tag/v4.4.1)

**Comment by reliq** [comment]
Thank you for reporting this. The issue was fixed in [v4.4.2](https://github.com/reliqarts/laravel-guided-image/releases/tag/v4.4.2)
